on:
  push:
    tags:
    - 'v*.*'

name: Release

jobs:

  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v3

    - name: Set environment variables
      id: vars
      run: |
        echo "ver=$(echo ${{ github.ref }} | sed -e's#.*/v##')" >> $GITHUB_OUTPUT

    - name: Dependency packages (apt)
      run: |
        sudo apt update
        sudo apt -y install git gcc-arm-none-eabi python3-pip srecord zip

    - name: Dependency packages (pip)
      run: python3 -m pip install --user crcmod

    - name: Build dist
      run: |
        make -j4 dist
        mv out/*.zip .

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: greaseweazle-firmware.ci.${{ steps.vars.outputs.ver }}
        path: greaseweazle-firmware-${{ steps.vars.outputs.ver }}.zip

  finalise:
    needs: build-ubuntu
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v3

    - name: Set environment variables
      id: vars
      run: |
        echo "ver=$(echo ${{ github.ref }} | sed -e's#.*/v##')" >> $GITHUB_OUTPUT

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: greaseweazle-firmware.ci.${{ steps.vars.outputs.ver }}

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Greaseweazle Firmware ${{ steps.vars.outputs.ver }}
        body: "[**Release Notes:**](https://github.com/keirf/greaseweazle-firmware/blob/master/RELEASE_NOTES)"
        draft: false
        prerelease: false
        artifacts: greaseweazle-firmware-${{ steps.vars.outputs.ver }}.zip
        artifactContentType: application/zip
